# Generated by Django 4.2.28 on 2026-02-22 13:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('800.00'))])),
                ('daily_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('remaining_payouts', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('200.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer')], default='MPESA', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_code', models.CharField(blank=True, help_text='M-Pesa or bank transaction code', max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('currency', models.CharField(default='KSH', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('national_id_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='kyc/ids/front/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='kyc/ids/back/')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='XMR.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INVESTMENT', 'Investment'), ('PROFIT', 'Profit'), ('REFERRAL_BONUS', 'Referral Bonus'), ('PENALTY', 'Penalty'), ('ADJUSTMENT', 'Admin Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing')], db_index=True, default='PENDING', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_entries', to='XMR.investment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='XMR.wallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_entries', to='XMR.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('token_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=20)),
                ('daily_return', models.DecimalField(decimal_places=2, help_text='Daily return in KSH', max_digits=10)),
                ('return_days', models.IntegerField(default=12, help_text='Number of days returns are paid')),
                ('total_return', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMING_SOON', 'Coming Soon'), ('SOLD_OUT', 'Sold Out')], db_index=True, default='ACTIVE', max_length=20)),
                ('max_purchases_per_user', models.IntegerField(default=1, help_text='Maximum times a user can buy this token')),
                ('total_supply', models.IntegerField(blank=True, help_text='Total available tokens, null for unlimited', null=True)),
                ('purchased_count', models.IntegerField(default=0, editable=False)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome or custom icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
            ],
            options={
                'ordering': ['token_number'],
                'indexes': [models.Index(fields=['status', 'token_number'], name='XMR_token_status_fbac2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('ADMIN_ACTION', 'Admin Action')], db_index=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('800.00'))])),
                ('phone_number', models.CharField(max_length=15)),
                ('mpesa_message', models.TextField(help_text='Full M-Pesa confirmation message')),
                ('mpesa_screenshot', models.ImageField(blank=True, null=True, upload_to='mpesa/screenshots/%Y/%m/%d/')),
                ('mpesa_code', models.CharField(blank=True, db_index=True, help_text='Extracted M-Pesa transaction code', max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payment', to='XMR.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='XMR.token'),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_purchase', to='XMR.transaction'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='XMR_withdra_user_id_4edb55_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='XMR_withdra_status_98fb06_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['request_id'], name='XMR_withdra_request_0e2468_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'balance'], name='XMR_wallet_user_id_c71007_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['referral_code'], name='XMR_userpro_referra_8ed72e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='XMR_userpro_phone_n_df7076_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-created_at'], name='XMR_userpro_created_5cf7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='XMR_transac_transac_91448c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status'], name='XMR_transac_wallet__7a7447_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='XMR_transac_wallet__03d03b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='XMR_transac_created_e5688f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_type', '-created_at'], name='XMR_systeml_log_typ_10f157_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', '-created_at'], name='XMR_systeml_user_id_0c3bad_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['mpesa_code'], name='XMR_mpesapa_mpesa_c_49c7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['user', 'status'], name='XMR_mpesapa_user_id_7b7952_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['-created_at'], name='XMR_mpesapa_created_b335aa_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='XMR_investm_user_id_69dcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['end_date', 'status'], name='XMR_investm_end_dat_22ae00_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_id'], name='XMR_investm_investm_0efa7f_idx'),
        ),
    ]
